export type User = { id:string; username:string; display_name:string; role:'admin'|'user'; status:'active'|'disabled'; password_set:boolean; created_at:string; updated_at:string }
export type Resource = { id:string; resource_key:string; display_name:string; host:string; port:number; database_name:string; username:string; password_set:boolean; tls_mode:string; max_rows:number; max_write_rows:number; statement_timeout_ms:number; enabled:boolean; version:number; created_at:string; updated_at:string }
export type Grant = { id:string; principal_id:string; username:string; resource_id:string; resource_key:string; action:'schema_read'|'query_read'|'query_write'; require_reason:boolean; row_limit?:number; statement_timeout_ms?:number; created_at:string; updated_at:string }
export type Audit = { id:number; request_id:string; username?:string; resource_key?:string; tool:string; action?:string; sql_text?:string; outcome:string; row_count?:number; duration_ms?:number; error_code?:string; created_at:string }
export type AuditPage = { items:Audit[]; page:number; page_size:number; total:number; total_pages:number }
export type AccessGrant = { id:string; action:'schema_read'|'query_read'|'query_write'; require_reason:boolean; row_limit?:number; statement_timeout_ms?:number }
export type PrincipalAccess = { resource_id:string; resource_key:string; display_name:string; database_name:string; enabled:boolean; grants:AccessGrant[] }
export type AccessResponse = { items:PrincipalAccess[] }
export type APIToken = { id:string; name:string; prefix:string; expires_at?:string; revoked_at?:string; created_at:string; config_available:boolean }
export type TokenResponse = { items:APIToken[] }
